### ISSUE TITLE
Error: Cannot find module 'npm' on mac

### ISSUE THREAD

**Issue by jbaf** [blitzrk/libsass-build-sublime#4]
Hello,

First, thanks for your plugin. It's the only one like it so far and I hope I'll be able to get it to work.
for now, I keep getting this error when I try to build my scss :  

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/myname/Library/Application Support/Sublime Text 3/Packages/libsass-build-sublime/build.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
[Finished in 0.1s with exit code 1]
[cmd: ['node', '/Users/myname/Library/Application Support/Sublime Text 3/Packages/libsass-build-sublime/build.js', '/Volumes/Web/myWorkingDirectory/scss/composants/_arbosousmenu.scss', '/Users/myname/Library/Application Support/Sublime Text 3/Packages/User/LibSassBuild.sublime-settings']]
[dir: /Volumes/Web/myWorkingDirectory]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

```

FYI : 
- I work on macOSX 10.11.2 (El Capitan), with Sublime Text 3
- My node-sass version is 3.3.3 and libsass 3.2.5
- when I echo my PATH in a terminal, I get "/Users/myname/npm/bin" and my NODE_PATH points to "/Users/myname/npm/lib/node_modules".

I left the content of libsass.sublime-build as it was originaly, like this :

```

{
    "cmd": [ 
        "node", 
        "$packages/libsass-build-sublime/build.js", 
        "$file", 
        "$packages/User/LibSassBuild.sublime-settings" 
    ],
    "working_dir": "$file_path",
    "selector": "source.scss, source.sass",
    "osx": { "path": "/usr/local/bin:$PATH" }
}

```

I tried some things, like changing my PATH and NODE_PATH, updating my node-sass and npm versions, but nothing did it...
Initiating node-sass via command line work fine on my computer, but no way to get it to work with your plugin in ST3. I would really like it, though. And as I'm quite a noob with all this npm stuff, it's pretty hard for me to isolate the problem by myself.

Feel free to ask me for more infos, if needed.
Thanks in advance for your time.

**Comment by blitzrk** [comment]
My implementation was shortsighted. I've decided to completely rewrite this project so that node isn't needed at all. I should have something working within a week. I'll update this issue when it's done.

It will have no external dependencies, require less config, and be installable with PackageControl.

**Comment by jbaf** [comment]
Great ! That would be wonderful !
I really look forward to it !

If I may emit an idea, please think about letting the possibility to store
the compiled css files in a different folder than the scss source files. I
have seen some plugins which didn't, and that's a key feature in lot
opinion.

Anyway, I can't wait for your new plugin ! Thanks again !

**Comment by blitzrk** [comment]
The new Libsass Build has been submitted to the Package Control repo. Hopefully it'll get pulled within a few days. I'll update again when it does. And it does allow for changing the output dir (though not much else yet).

**Comment by jbaf** [comment]
Great ! I'll give it a try as soon as I can. Thank you.

**Comment by blitzrk** [comment]
It took a while, but it's now been merged into PC. Search for libsass and you'll find it. :)
